//go:build ignore

/*
Copyright 2026 Brian Morton.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-version-matrix generates internal/temporal/versions_gen.go from
// hack/version-matrix.yaml. Run via `make gen-version-matrix` (or
// `go run hack/gen-version-matrix.go`).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"

	"sigs.k8s.io/yaml"
)

type versionInfo struct {
	Version                      string   `json:"version"`
	PatchVersions                []string `json:"patchVersions"`
	MinSchemaSQL                 string   `json:"minSchemaSQL"`
	MinSchemaCassandra           string   `json:"minSchemaCassandra"`
	MinSchemaES                  string   `json:"minSchemaES"`
	AllowedFromVersions          []string `json:"allowedFromVersions"`
	UISeries                     string   `json:"uiSeries"`
	DefaultUIVersion             string   `json:"defaultUIVersion"`
	DevServerCLIVersion          string   `json:"devServerCLIVersion"`
	CassandraVisibilitySupported bool     `json:"cassandraVisibilitySupported"`
	RemovedDynamicConfig         []string `json:"removedDynamicConfig"`
	AddedDynamicConfig           []string `json:"addedDynamicConfig"`
}

type matrix struct {
	Versions []versionInfo `json:"versions"`
}

const outputTemplate = `// Code generated by hack/gen-version-matrix.go; DO NOT EDIT.
// Source: hack/version-matrix.yaml

package temporal

// supportedVersions is the generated Temporal version compatibility matrix.
var supportedVersions = []VersionInfo{
{{- range .Versions }}
	{
		Version:                      {{ printf "%q" .Version }},
		PatchVersions:                {{ strSlice .PatchVersions }},
		MinSchemaSQL:                 {{ printf "%q" .MinSchemaSQL }},
		MinSchemaCassandra:           {{ printf "%q" .MinSchemaCassandra }},
		MinSchemaES:                  {{ printf "%q" .MinSchemaES }},
		AllowedFromVersions:          {{ strSlice .AllowedFromVersions }},
		UISeries:                     {{ printf "%q" .UISeries }},
		DefaultUIVersion:             {{ printf "%q" .DefaultUIVersion }},
		DevServerCLIVersion:          {{ printf "%q" .DevServerCLIVersion }},
		CassandraVisibilitySupported: {{ .CassandraVisibilitySupported }},
		RemovedDynamicConfig:         {{ strSlice .RemovedDynamicConfig }},
		AddedDynamicConfig:           {{ strSlice .AddedDynamicConfig }},
	},
{{- end }}
}
`

func strSlice(items []string) string {
	if len(items) == 0 {
		return "nil"
	}
	out := "[]string{"
	for i, s := range items {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("%q", s)
	}
	out += "}"
	return out
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-version-matrix:", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := os.ReadFile("hack/version-matrix.yaml")
	if err != nil {
		return err
	}
	var m matrix
	if err := yaml.Unmarshal(data, &m); err != nil {
		return err
	}

	tmpl, err := template.New("gen").Funcs(template.FuncMap{"strSlice": strSlice}).Parse(outputTemplate)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w\n%s", err, buf.String())
	}
	return os.WriteFile("internal/temporal/versions_gen.go", formatted, 0o644)
}
