## Append samples of your project ##
resources:
- temporal_v1alpha1_temporalcluster.yaml
- temporal_v1alpha1_temporalnamespace.yaml
- temporal_v1alpha1_temporalsearchattribute.yaml
- temporal_v1alpha1_temporalclusterclient.yaml
- temporal_v1alpha1_temporalschedule.yaml
- temporal_v1alpha1_temporaldevserver.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
