apiVersion: temporal.bmor10.com/v1alpha1
kind: TemporalClusterClient
metadata:
  labels:
    app.kubernetes.io/name: temporal-operator
    app.kubernetes.io/managed-by: kustomize
  name: temporalclusterclient-sample
spec:
  clusterRef:
    name: temporalcluster-sample
  secretName: temporalcluster-sample-client
