apiVersion: temporal.bmor10.com/v1alpha1
kind: TemporalSearchAttribute
metadata:
  labels:
    app.kubernetes.io/name: temporal-operator
    app.kubernetes.io/managed-by: kustomize
  name: temporalsearchattribute-sample
spec:
  clusterRef:
    name: temporalcluster-sample
  namespace: default
  name: CustomerId
  type: Keyword
