apiVersion: temporal.bmor10.com/v1alpha1
kind: TemporalClusterConnection
metadata:
  name: dr-pair
spec:
  peers:
    - name: clusterA
      clusterRef:
        name: cluster-a
    - name: clusterB
      clusterRef:
        name: cluster-b
