name: DCO

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read

jobs:
  dco:
    name: DCO check
    runs-on: namespace-profile-temporal-operator
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tim-actions/get-pr-commits@master
        id: get_pr_commits
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: tim-actions/dco@v1.1.0
        with:
          commits: ${{ steps.get_pr_commits.outputs.commits }}
